# Generated by Django 4.1.13 on 2025-10-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
