# Generated by Django 4.1.13 on 2025-10-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0002_inventoryitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
    ]
