# Generated by Django 4.1.13 on 2025-10-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0003_remove_inventoryitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='maximum_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
