# Generated by Django 6.0.1 on 2026-01-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0004_inventoryitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=20, verbose_name='Position'),
        ),
    ]
